version: "3.8"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ratelimiter
      POSTGRES_USER: rl
      POSTGRES_PASSWORD: rl
    ports:
      - "5432:5432"
